language: bash

env:
  global:
    - POSTGRES_DB=test
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=pass
    - JWT_SECRET=seGHYFcret14khbg38%fhbg73345F56uyFVHfcsgjhjj2y53v87tv87&%C&c6vbbn
    - PGRST_SERVER_PROXY_URI=http://localhost:3000
    - PGRST_AUTHENTICATOR_PASSWORD=authpass
    - OAUTH_ACCESS_TOKEN_JWT_SECRET=morethan32symbolssecretkey!!!!!!
    - OAUTH_ACCESS_TOKEN_TTL=7200
    - OAUTH_REFRESH_TOKEN_JWT_SECRET=notlesshan32symbolssecretkey!!!!
    - OAUTH_COOKIE_HASH_KEY=supersecret
    - OAUTH_COOKIE_BLOCK_KEY=16charssecret!!!
    - OAUTH_VALIDATE_REDIRECT_URI=false

before_install:

  - sudo apt-get update

  - sudo apt-get install docker-ce

  - sudo curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

  - sudo chmod +x /usr/local/bin/docker-compose

  - docker --version

  - docker-compose --version

  - sudo apt-get install npm

  - npm install newman --global

script:


